### ISSUE TITLE
imagehash

### ISSUE THREAD

**Issue by JohannesBuchner** [axeltidemann/self_dot#6]
I see that you also have a imagehash implementation of phash, ahash, dhash in utils.py. In case it is based on imagehash (https://github.com/JohannesBuchner/imagehash), please consider updating to the latest version - we fixed some important bugs (see Changelog).
Alternatively, you can import the module imagehash (it is in pypi) via setup.py and through that always get the latest version.

**Comment by axeltidemann** [comment]
Thanks for the update! We are in the process of reviving the project, and I'll put this on our to-do list.
